version: "3.7"

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cofoundry
    ports:
      - 5000:80
    depends_on:
      - db
  db:
    hostname: sql1 # same hostname as appsetting.json
    image: "microsoft/mssql-server-linux"
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    volumes:
      - database:/var/opt/mssql/data
volumes:
  database:
    


    