version: '3.5'

networks:
  db_net:

volumes:
  cms-shared:
  dbdata:
  esdata:

services:
  app:
    build:
      context: keystone-kto
      dockerfile: Dockerfile
    image: keystone-kto
    environment:
      SESSION_SECRET: 79aa63fc-ee15-4df7-b211-b42929aa6448
      CREATE_TABLES: "true"
    ports:
      - 3000:3000
    networks:
      - db_net
    depends_on:
      - db

  db:
    hostname: pg
    image: postgres:11
    command: postgres -c 'max_connections=400' -c 'shared_buffers=128MB'
    environment:
        "POSTGRES_USER": 'keystone'
        "POSTGRES_PASSWORD": 'password'
        "POSTGRES_DB": 'keystone'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - db_net
