services:
    db:
        image: 'mongo:latest'
        volumes:
        - 'mongo-vol:/data/db'
        networks:
        - cockpit
    cms:
        image: agentejo/cockpit
        environment:
            COCKPIT_SESSION_NAME: cockpit
            COCKPIT_SALT: 670d8d60-134b-4e9d-b1a4-fd8ed2fa3aeb
            COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
            COCKPIT_DATABASE_NAME: cockpit_master
        depends_on:
        - db
        ports:
        - "8080:80"
        networks:
        - cockpit
networks:
    cockpit:
        driver: bridge
volumes:
    mongo-vol: null